: STAR 42 emit ;
: STARS 0 do STAR loop ;
: MARGIN cr 30 spaces ;
: BLIP MARGIN STAR ;
: IOI MARGIN STAR ."   " STAR ;
: IIO MARGIN STAR STAR ."   " ;
: OIO MARGIN ."  " STAR ."  ";
: BAR MARGIN 5 STARS ;
: F BAR BLIP BAR BLIP BLIP cr ;
: O BAR IOI IOI IOI BAR cr ;
: R BAR IOI BAR IIO IOI cr ;
: T BAR OIO OIO OIO OIO cr ;
: H IOI IOI BAR IOI IOI cr ;
F O R T H